# Generated by Django 2.1.4 on 2019-05-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='enrl_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
